jaco:
  # Publish all joint states -----------------------------------
  joint_state_controller:
    type: joint_state_controller/JointStateController
    publish_rate: 50  

  # Position Controllers ---------------------------------------
  joint_1_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_1
    pid: {p: 125.0, i: 0.01, d: 13.5}
  joint_2_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_2
    pid: {p: 5.0, i: 0.01, d: 10.0}     
  joint_3_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_3
    pid: {p: 100.0, i: 0.01, d: 10.0}
  joint_4_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_4
    pid: {p: 140, i: 0.01, d: 5.0}
  joint_5_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_5
    pid: {p: 180.0, i: 0.01, d: 7.0}
  joint_6_position_controller:
    type: effort_controllers/JointPositionController
    joint: joint_6
    pid: {p: 160.0, i: 0.01, d: 2.5}        
